name: Build GBA rom
on:
  push:
    branches:
      - acceptance

jobs:
  build-rom:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20200730

    steps:
      - name: Checkout w/ submodules
        uses: actions/checkout@v2.3.1
        with:
          submodules: true

      - name: Build GBA rom
        run: |
          make -j$(nproc)