name: Build GBA rom
on:
  push:
    branches:
      - acceptance

jobs:
  build-rom:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20200730

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save Me plz
        run: |
          pwd
          ls -la

      - name: Build GBA rom
        run: |
          make -j$(nproc)