name: Build GBA rom
on:
  push:
    branches:
      - acceptance

jobs:
  build-rom:
    runs-on: ubuntu-latest
    steps:
      - name: Install devkitPro GBA
        run: |
          sudo apt update && sudo apt install gdebi -y
          wget -O dkp-pacman.deb https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
          sudo gdebi dkp-pacman.deb
          sudo dkp-pacman -Syu --no-confirm gba-dev

      - name: Checkout
        uses: actions/checkout@v2.3.1
      
      - name: Get Butano submodule
        run : |
          git submodule update --init

      - name: Build rom
        run: |
          make -j$(nproc)